### ISSUE TITLE
Minitalk : 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by slink7** [xicodomingues/francinette#87]
On WSL, (Ubuntu 20.04.6 LTS)

I get an error when i try to run francinette in my minitalk project,

> 2024-01-19 22:31:40,688 [base][ERROR]: 'NoneType' object has no attribute 'group'
> Traceback (most recent call last):
>   File "/home/slink/francinette/testers/BaseTester.py", line 183, in test_using
>     return (tester.name, tx.execute())
>   File "/home/slink/francinette/testers/minitalk/Fsoares.py", line 77, in execute
>     result = self.test_client_server()
>   File "/home/slink/francinette/testers/minitalk/Fsoares.py", line 96, in test_client_server
>     no_leaks = self.test_leaks()
>   File "/home/slink/francinette/testers/minitalk/Fsoares.py", line 243, in test_leaks
>     self.send_message(server, "teste\n-----\n")
>   File "/home/slink/francinette/testers/minitalk/Fsoares.py", line 275, in send_message
>     return re.match(r"__PID: (\d+)", client.stdout.decode('utf-8', errors="backslashreplace")).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

**Additional information**
[execution.log](https://github.com/xicodomingues/francinette/files/13994868/execution.log)
![image](https://github.com/xicodomingues/francinette/assets/75044895/72e45179-d8a3-49ca-8d5b-20455dfab5a7)

**Comment by ownleex** [comment]
Hello,
I get the same error as you. Have you found the solution?

**Comment by rinelfi-git** [comment]
same

**Comment by ownleex** [comment]
Hello, in my case the project was validated with this error.

**Comment by alternateash** [comment]
I got this too, too scared to submit yet as blackhole looms and can't afford the 2 day cooldown

**Comment by ownleex** [comment]
As a reminder, there is no moulinette on this project ;)
